CREATE TABLE Post (
  PostId SERIAL PRIMARY KEY,
  Title VARCHAR(255) NOT NULL,
  Content TEXT NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE Comment (
  CommentId SERIAL PRIMARY KEY,
  PostId INTEGER NOT NULL REFERENCES Post(PostId),
  Text TEXT NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT now()
);